// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpwbqujwrmkzkqnkzhzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impwd2JxdWp3cm1remtxbmt6aHppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNDc1NTEsImV4cCI6MjA1OTgyMzU1MX0.GudSlD3VGU5OzNoXTQjmwk0-zEq8pEVf-NEhRGBYAaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);